# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/python-poetry/poetry
    rev: 3e5e038ca84330a814ba2a2fd808b19d6ffad031
    hooks:
      - id: poetry-check  # TODO enable with release of poetry 2.0
      - id: poetry-lock
  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: ee112383b503288be4adc9137a53f2d8c738dabc
    hooks:
      - id: poetry-export
        args: ["--all-extras"]
