[project]
name = "nakasvr"
dynamic = ["version"]
description = "Connect a remote kernel with a local Spyder IDE"
authors = [
    {name = "Simon McIntosh",email = "simon.mcintosh@iter.org"}
]
readme = "README.md"
requires-python = ">=3.10,<4"
dependencies = [
  "click (>=8.1.7,<9.0.0)",
  "fabric (>=3.2.2,<4.0.0)",
  "spyder<6",
  "fsspec (>=2024.10.0,<2025.0.0)",
  "numpy (>=2.1.2,<3.0.0)",
  "appdirs (>=1.4.4,<2.0.0)",
  "logging (>=0.4.9.6,<0.5.0.0)",
  "spyder-kernels",
]


[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry]
version = "0.0.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.1"

[project.scripts]
lanuch_kernel = "nakasvr.lanuch:lanuch"
copy_kernel = "nakasvr.copy:copy"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
pattern = "^(?P<base>\\d+\\.\\d+\\.\\d+)(-?((?P<stage>[a-zA-Z]+)\\.?(?P<revision>\\d+)?))?"
format = "{base}+{distance}.{commit}"
